// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sonic.proto

/*
Package gnoi_sonic is a generated protocol buffer package.

It is generated from these files:
	sonic.proto

It has these top-level messages:
	TechsupportRequest
	TechsupportResponse
	SumRequest
	SumResponse
	SaveConfigRequest
	SaveConfigResponse
	ReloadConfigRequest
	ReloadConfigResponse
	LoadMgmtConfigRequest
	LoadMgmtConfigResponse
	LoadMinigraphRequest
	LoadMinigraphResponse
*/
package gnoi_sonic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TechsupportRequest struct {
	Input *TechsupportRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *TechsupportRequest) Reset()                    { *m = TechsupportRequest{} }
func (m *TechsupportRequest) String() string            { return proto.CompactTextString(m) }
func (*TechsupportRequest) ProtoMessage()               {}
func (*TechsupportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TechsupportRequest) GetInput() *TechsupportRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type TechsupportRequest_Input struct {
	Date string `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
}

func (m *TechsupportRequest_Input) Reset()                    { *m = TechsupportRequest_Input{} }
func (m *TechsupportRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*TechsupportRequest_Input) ProtoMessage()               {}
func (*TechsupportRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *TechsupportRequest_Input) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type TechsupportResponse struct {
	Output *TechsupportResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *TechsupportResponse) Reset()                    { *m = TechsupportResponse{} }
func (m *TechsupportResponse) String() string            { return proto.CompactTextString(m) }
func (*TechsupportResponse) ProtoMessage()               {}
func (*TechsupportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TechsupportResponse) GetOutput() *TechsupportResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type TechsupportResponse_Output struct {
	OutputFilename string `protobuf:"bytes,1,opt,name=output_filename,json=outputFilename" json:"output_filename,omitempty"`
}

func (m *TechsupportResponse_Output) Reset()                    { *m = TechsupportResponse_Output{} }
func (m *TechsupportResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*TechsupportResponse_Output) ProtoMessage()               {}
func (*TechsupportResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *TechsupportResponse_Output) GetOutputFilename() string {
	if m != nil {
		return m.OutputFilename
	}
	return ""
}

type SumRequest struct {
	Input *SumRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SumRequest) GetInput() *SumRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type SumRequest_Input struct {
	Left  int32 `protobuf:"varint,1,opt,name=left" json:"left,omitempty"`
	Right int32 `protobuf:"varint,2,opt,name=right" json:"right,omitempty"`
}

func (m *SumRequest_Input) Reset()                    { *m = SumRequest_Input{} }
func (m *SumRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*SumRequest_Input) ProtoMessage()               {}
func (*SumRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *SumRequest_Input) GetLeft() int32 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *SumRequest_Input) GetRight() int32 {
	if m != nil {
		return m.Right
	}
	return 0
}

type SumResponse struct {
	Output *SumResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SumResponse) GetOutput() *SumResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type SumResponse_Output struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *SumResponse_Output) Reset()                    { *m = SumResponse_Output{} }
func (m *SumResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*SumResponse_Output) ProtoMessage()               {}
func (*SumResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *SumResponse_Output) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SaveConfigRequest struct {
	Input *SaveConfigRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *SaveConfigRequest) Reset()                    { *m = SaveConfigRequest{} }
func (m *SaveConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveConfigRequest) ProtoMessage()               {}
func (*SaveConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveConfigRequest) GetInput() *SaveConfigRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type SaveConfigRequest_Input struct {
	FilePath string `protobuf:"bytes,1,opt,name=FilePath" json:"FilePath,omitempty"`
}

func (m *SaveConfigRequest_Input) Reset()                    { *m = SaveConfigRequest_Input{} }
func (m *SaveConfigRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*SaveConfigRequest_Input) ProtoMessage()               {}
func (*SaveConfigRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *SaveConfigRequest_Input) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type SaveConfigResponse struct {
	Output *SaveConfigResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *SaveConfigResponse) Reset()                    { *m = SaveConfigResponse{} }
func (m *SaveConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveConfigResponse) ProtoMessage()               {}
func (*SaveConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SaveConfigResponse) GetOutput() *SaveConfigResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type SaveConfigResponse_Output struct {
	Status string `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *SaveConfigResponse_Output) Reset()                    { *m = SaveConfigResponse_Output{} }
func (m *SaveConfigResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*SaveConfigResponse_Output) ProtoMessage()               {}
func (*SaveConfigResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *SaveConfigResponse_Output) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReloadConfigRequest struct {
	Input *ReloadConfigRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *ReloadConfigRequest) Reset()                    { *m = ReloadConfigRequest{} }
func (m *ReloadConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ReloadConfigRequest) ProtoMessage()               {}
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReloadConfigRequest) GetInput() *ReloadConfigRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type ReloadConfigRequest_Input struct {
	FilePath string `protobuf:"bytes,1,opt,name=FilePath" json:"FilePath,omitempty"`
}

func (m *ReloadConfigRequest_Input) Reset()                    { *m = ReloadConfigRequest_Input{} }
func (m *ReloadConfigRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*ReloadConfigRequest_Input) ProtoMessage()               {}
func (*ReloadConfigRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *ReloadConfigRequest_Input) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type ReloadConfigResponse struct {
	Output *ReloadConfigResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *ReloadConfigResponse) Reset()                    { *m = ReloadConfigResponse{} }
func (m *ReloadConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ReloadConfigResponse) ProtoMessage()               {}
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReloadConfigResponse) GetOutput() *ReloadConfigResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type ReloadConfigResponse_Output struct {
	Status string `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *ReloadConfigResponse_Output) Reset()                    { *m = ReloadConfigResponse_Output{} }
func (m *ReloadConfigResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*ReloadConfigResponse_Output) ProtoMessage()               {}
func (*ReloadConfigResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *ReloadConfigResponse_Output) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type LoadMgmtConfigRequest struct {
	Input *LoadMgmtConfigRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *LoadMgmtConfigRequest) Reset()                    { *m = LoadMgmtConfigRequest{} }
func (m *LoadMgmtConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*LoadMgmtConfigRequest) ProtoMessage()               {}
func (*LoadMgmtConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LoadMgmtConfigRequest) GetInput() *LoadMgmtConfigRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type LoadMgmtConfigRequest_Input struct {
	FilePath string `protobuf:"bytes,1,opt,name=FilePath" json:"FilePath,omitempty"`
}

func (m *LoadMgmtConfigRequest_Input) Reset()                    { *m = LoadMgmtConfigRequest_Input{} }
func (m *LoadMgmtConfigRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*LoadMgmtConfigRequest_Input) ProtoMessage()               {}
func (*LoadMgmtConfigRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *LoadMgmtConfigRequest_Input) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type LoadMgmtConfigResponse struct {
	Output *LoadMgmtConfigResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *LoadMgmtConfigResponse) Reset()                    { *m = LoadMgmtConfigResponse{} }
func (m *LoadMgmtConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*LoadMgmtConfigResponse) ProtoMessage()               {}
func (*LoadMgmtConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LoadMgmtConfigResponse) GetOutput() *LoadMgmtConfigResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type LoadMgmtConfigResponse_Output struct {
	Status string `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *LoadMgmtConfigResponse_Output) Reset()         { *m = LoadMgmtConfigResponse_Output{} }
func (m *LoadMgmtConfigResponse_Output) String() string { return proto.CompactTextString(m) }
func (*LoadMgmtConfigResponse_Output) ProtoMessage()    {}
func (*LoadMgmtConfigResponse_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

func (m *LoadMgmtConfigResponse_Output) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type LoadMinigraphRequest struct {
	Input *LoadMinigraphRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *LoadMinigraphRequest) Reset()                    { *m = LoadMinigraphRequest{} }
func (m *LoadMinigraphRequest) String() string            { return proto.CompactTextString(m) }
func (*LoadMinigraphRequest) ProtoMessage()               {}
func (*LoadMinigraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LoadMinigraphRequest) GetInput() *LoadMinigraphRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type LoadMinigraphRequest_Input struct {
	FilePath string `protobuf:"bytes,1,opt,name=FilePath" json:"FilePath,omitempty"`
}

func (m *LoadMinigraphRequest_Input) Reset()                    { *m = LoadMinigraphRequest_Input{} }
func (m *LoadMinigraphRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*LoadMinigraphRequest_Input) ProtoMessage()               {}
func (*LoadMinigraphRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

func (m *LoadMinigraphRequest_Input) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type LoadMinigraphResponse struct {
	Output *LoadMinigraphResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *LoadMinigraphResponse) Reset()                    { *m = LoadMinigraphResponse{} }
func (m *LoadMinigraphResponse) String() string            { return proto.CompactTextString(m) }
func (*LoadMinigraphResponse) ProtoMessage()               {}
func (*LoadMinigraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LoadMinigraphResponse) GetOutput() *LoadMinigraphResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type LoadMinigraphResponse_Output struct {
	Status string `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *LoadMinigraphResponse_Output) Reset()         { *m = LoadMinigraphResponse_Output{} }
func (m *LoadMinigraphResponse_Output) String() string { return proto.CompactTextString(m) }
func (*LoadMinigraphResponse_Output) ProtoMessage()    {}
func (*LoadMinigraphResponse_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

func (m *LoadMinigraphResponse_Output) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*TechsupportRequest)(nil), "gnoi.sonic.TechsupportRequest")
	proto.RegisterType((*TechsupportRequest_Input)(nil), "gnoi.sonic.TechsupportRequest.Input")
	proto.RegisterType((*TechsupportResponse)(nil), "gnoi.sonic.TechsupportResponse")
	proto.RegisterType((*TechsupportResponse_Output)(nil), "gnoi.sonic.TechsupportResponse.Output")
	proto.RegisterType((*SumRequest)(nil), "gnoi.sonic.SumRequest")
	proto.RegisterType((*SumRequest_Input)(nil), "gnoi.sonic.SumRequest.Input")
	proto.RegisterType((*SumResponse)(nil), "gnoi.sonic.SumResponse")
	proto.RegisterType((*SumResponse_Output)(nil), "gnoi.sonic.SumResponse.Output")
	proto.RegisterType((*SaveConfigRequest)(nil), "gnoi.sonic.SaveConfigRequest")
	proto.RegisterType((*SaveConfigRequest_Input)(nil), "gnoi.sonic.SaveConfigRequest.Input")
	proto.RegisterType((*SaveConfigResponse)(nil), "gnoi.sonic.SaveConfigResponse")
	proto.RegisterType((*SaveConfigResponse_Output)(nil), "gnoi.sonic.SaveConfigResponse.Output")
	proto.RegisterType((*ReloadConfigRequest)(nil), "gnoi.sonic.ReloadConfigRequest")
	proto.RegisterType((*ReloadConfigRequest_Input)(nil), "gnoi.sonic.ReloadConfigRequest.Input")
	proto.RegisterType((*ReloadConfigResponse)(nil), "gnoi.sonic.ReloadConfigResponse")
	proto.RegisterType((*ReloadConfigResponse_Output)(nil), "gnoi.sonic.ReloadConfigResponse.Output")
	proto.RegisterType((*LoadMgmtConfigRequest)(nil), "gnoi.sonic.LoadMgmtConfigRequest")
	proto.RegisterType((*LoadMgmtConfigRequest_Input)(nil), "gnoi.sonic.LoadMgmtConfigRequest.Input")
	proto.RegisterType((*LoadMgmtConfigResponse)(nil), "gnoi.sonic.LoadMgmtConfigResponse")
	proto.RegisterType((*LoadMgmtConfigResponse_Output)(nil), "gnoi.sonic.LoadMgmtConfigResponse.Output")
	proto.RegisterType((*LoadMinigraphRequest)(nil), "gnoi.sonic.LoadMinigraphRequest")
	proto.RegisterType((*LoadMinigraphRequest_Input)(nil), "gnoi.sonic.LoadMinigraphRequest.Input")
	proto.RegisterType((*LoadMinigraphResponse)(nil), "gnoi.sonic.LoadMinigraphResponse")
	proto.RegisterType((*LoadMinigraphResponse_Output)(nil), "gnoi.sonic.LoadMinigraphResponse.Output")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SonicService service

type SonicServiceClient interface {
	ShowTechsupport(ctx context.Context, in *TechsupportRequest, opts ...grpc.CallOption) (*TechsupportResponse, error)
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	LoadMgmtConfig(ctx context.Context, in *LoadMgmtConfigRequest, opts ...grpc.CallOption) (*LoadMgmtConfigResponse, error)
	LoadMinigraph(ctx context.Context, in *LoadMinigraphRequest, opts ...grpc.CallOption) (*LoadMinigraphResponse, error)
}

type sonicServiceClient struct {
	cc *grpc.ClientConn
}

func NewSonicServiceClient(cc *grpc.ClientConn) SonicServiceClient {
	return &sonicServiceClient{cc}
}

func (c *sonicServiceClient) ShowTechsupport(ctx context.Context, in *TechsupportRequest, opts ...grpc.CallOption) (*TechsupportResponse, error) {
	out := new(TechsupportResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/ShowTechsupport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	out := new(SaveConfigResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/SaveConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	out := new(ReloadConfigResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/ReloadConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) LoadMgmtConfig(ctx context.Context, in *LoadMgmtConfigRequest, opts ...grpc.CallOption) (*LoadMgmtConfigResponse, error) {
	out := new(LoadMgmtConfigResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/LoadMgmtConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) LoadMinigraph(ctx context.Context, in *LoadMinigraphRequest, opts ...grpc.CallOption) (*LoadMinigraphResponse, error) {
	out := new(LoadMinigraphResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/LoadMinigraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SonicService service

type SonicServiceServer interface {
	ShowTechsupport(context.Context, *TechsupportRequest) (*TechsupportResponse, error)
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error)
	LoadMgmtConfig(context.Context, *LoadMgmtConfigRequest) (*LoadMgmtConfigResponse, error)
	LoadMinigraph(context.Context, *LoadMinigraphRequest) (*LoadMinigraphResponse, error)
}

func RegisterSonicServiceServer(s *grpc.Server, srv SonicServiceServer) {
	s.RegisterService(&_SonicService_serviceDesc, srv)
}

func _SonicService_ShowTechsupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechsupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).ShowTechsupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/ShowTechsupport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).ShowTechsupport(ctx, req.(*TechsupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/SaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_LoadMgmtConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMgmtConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).LoadMgmtConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/LoadMgmtConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).LoadMgmtConfig(ctx, req.(*LoadMgmtConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_LoadMinigraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMinigraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).LoadMinigraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/LoadMinigraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).LoadMinigraph(ctx, req.(*LoadMinigraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SonicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnoi.sonic.SonicService",
	HandlerType: (*SonicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowTechsupport",
			Handler:    _SonicService_ShowTechsupport_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _SonicService_Sum_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _SonicService_SaveConfig_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _SonicService_ReloadConfig_Handler,
		},
		{
			MethodName: "LoadMgmtConfig",
			Handler:    _SonicService_LoadMgmtConfig_Handler,
		},
		{
			MethodName: "LoadMinigraph",
			Handler:    _SonicService_LoadMinigraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sonic.proto",
}

func init() { proto.RegisterFile("sonic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xdf, 0x6b, 0xd3, 0x50,
	0x14, 0xc7, 0x53, 0x67, 0x8b, 0x9e, 0xce, 0x0d, 0xcf, 0x6a, 0x1d, 0x51, 0xbb, 0xee, 0x4e, 0xb7,
	0xf9, 0x12, 0x58, 0x05, 0xf1, 0xd7, 0xfc, 0x81, 0x20, 0x08, 0x0e, 0x25, 0x19, 0x82, 0x4f, 0x12,
	0xdb, 0xdb, 0x24, 0xd0, 0xe4, 0xc6, 0xe4, 0x66, 0x63, 0x88, 0xef, 0xfe, 0xc3, 0xbe, 0x4b, 0x6f,
	0x6e, 0x9a, 0xdc, 0xb4, 0x4d, 0x24, 0x6f, 0xf7, 0x1c, 0xce, 0xf9, 0x7e, 0xfb, 0xb9, 0xbd, 0xe7,
	0x04, 0xba, 0x31, 0x0b, 0xbc, 0xb1, 0x11, 0x46, 0x8c, 0x33, 0x04, 0x27, 0x60, 0x9e, 0x21, 0x32,
	0xc4, 0x07, 0x3c, 0xa7, 0x63, 0x37, 0x4e, 0xc2, 0x90, 0x45, 0xdc, 0xa4, 0x3f, 0x13, 0x1a, 0x73,
	0x7c, 0x01, 0x6d, 0x2f, 0x08, 0x13, 0xbe, 0xdb, 0x1a, 0xb6, 0x8e, 0xbb, 0xa3, 0x87, 0x46, 0xde,
	0x61, 0x2c, 0x97, 0x1b, 0x1f, 0xe7, 0xb5, 0x66, 0xda, 0xa2, 0xdf, 0x83, 0xb6, 0x88, 0x11, 0xe1,
	0xfa, 0xc4, 0xe6, 0x54, 0x68, 0xdc, 0x34, 0xc5, 0x99, 0xfc, 0x69, 0xc1, 0x8e, 0x22, 0x10, 0x87,
	0x2c, 0x88, 0x29, 0xbe, 0x86, 0x0e, 0x4b, 0x78, 0xee, 0x78, 0xb8, 0xd6, 0x31, 0x6d, 0x30, 0x3e,
	0x8b, 0x6a, 0x53, 0x76, 0xe9, 0x27, 0xd0, 0x49, 0x33, 0x78, 0x04, 0xdb, 0x69, 0xee, 0xfb, 0xd4,
	0x9b, 0xd1, 0xc0, 0xf6, 0xb3, 0x1f, 0xb0, 0x95, 0xa6, 0x3f, 0xc8, 0x2c, 0x89, 0x01, 0xac, 0xc4,
	0xcf, 0x88, 0x47, 0x2a, 0xf1, 0xfd, 0xa2, 0x7f, 0x5e, 0xa6, 0x92, 0x9e, 0x14, 0x48, 0x67, 0x74,
	0x9a, 0xf6, 0xb6, 0x4d, 0x71, 0xc6, 0x1e, 0xb4, 0x23, 0xcf, 0x71, 0xf9, 0xee, 0x35, 0x91, 0x4c,
	0x03, 0xe2, 0x40, 0x57, 0xa8, 0x49, 0xec, 0xa7, 0x25, 0xec, 0xc1, 0x92, 0xed, 0x6a, 0xdc, 0xe1,
	0x02, 0xb7, 0x0f, 0x9d, 0x88, 0xc6, 0xc9, 0x2c, 0x33, 0x97, 0x11, 0x89, 0xe1, 0xb6, 0x65, 0x5f,
	0xd0, 0xf7, 0x2c, 0x98, 0x7a, 0x4e, 0x06, 0xf9, 0x5c, 0x85, 0x3c, 0x50, 0xdc, 0xca, 0xd5, 0x2a,
	0xeb, 0x41, 0xc6, 0xaa, 0xc3, 0x8d, 0xf9, 0x15, 0x7e, 0xb1, 0xb9, 0x2b, 0x2f, 0x76, 0x11, 0x93,
	0x04, 0xb0, 0x28, 0x23, 0x21, 0x4f, 0x4b, 0x90, 0x8f, 0xd6, 0xd9, 0xfe, 0x07, 0xab, 0xc5, 0x6d,
	0x9e, 0xc4, 0xd2, 0x58, 0x46, 0xe4, 0x12, 0x76, 0x4c, 0x3a, 0x63, 0xf6, 0x44, 0xa5, 0x7d, 0xa9,
	0xd2, 0x2a, 0xb6, 0x2b, 0xea, 0x1b, 0xf0, 0x5e, 0x41, 0x4f, 0x15, 0x92, 0xc4, 0x6f, 0x4a, 0xc4,
	0x47, 0xeb, 0xad, 0x9b, 0x32, 0xff, 0x82, 0x3b, 0x9f, 0x98, 0x3d, 0x39, 0x73, 0x7c, 0xae, 0x52,
	0x9f, 0xaa, 0xd4, 0x8a, 0xf5, 0xca, 0x8e, 0x06, 0xdc, 0xbf, 0xa1, 0x5f, 0x96, 0x92, 0xe4, 0xef,
	0x4a, 0xe4, 0x8f, 0xab, 0xec, 0x9b, 0xb2, 0x5f, 0x41, 0x4f, 0x48, 0x79, 0x81, 0xe7, 0x44, 0x76,
	0xe8, 0x66, 0xe8, 0xaf, 0x54, 0xf4, 0xc3, 0x25, 0xef, 0x52, 0x43, 0x03, 0xf2, 0xec, 0xda, 0x73,
	0x25, 0x09, 0xfe, 0xb6, 0x04, 0x7e, 0x5c, 0x61, 0xde, 0x90, 0x7b, 0xf4, 0x77, 0x03, 0x36, 0xad,
	0xb9, 0xa0, 0x45, 0xa3, 0x0b, 0x6f, 0x4c, 0xf1, 0x1c, 0xb6, 0x2d, 0x97, 0x5d, 0x16, 0xf6, 0x23,
	0x0e, 0xaa, 0x57, 0xb5, 0xbe, 0x57, 0xb3, 0x58, 0x89, 0x86, 0xcf, 0x60, 0xc3, 0x4a, 0x7c, 0xec,
	0xaf, 0x5e, 0x81, 0xfa, 0xdd, 0x35, 0x3b, 0x8a, 0x68, 0x78, 0x06, 0x90, 0xcf, 0x33, 0x3e, 0xa8,
	0x5c, 0x2f, 0xfa, 0xa0, 0x7a, 0x0d, 0x10, 0x0d, 0x2d, 0xd8, 0x2c, 0x0e, 0x0b, 0xee, 0xd5, 0x4c,
	0xb0, 0x3e, 0xac, 0x9b, 0x33, 0xa2, 0xe1, 0x37, 0xd8, 0x52, 0xdf, 0x21, 0xee, 0xd7, 0x8e, 0x88,
	0x4e, 0xea, 0x9f, 0x31, 0xd1, 0xf0, 0x2b, 0xdc, 0x52, 0xfe, 0x69, 0x1c, 0xd6, 0xbd, 0x40, 0x7d,
	0xbf, 0xf6, 0x99, 0x10, 0xed, 0x47, 0x47, 0x7c, 0xb6, 0x9f, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x1c, 0x4b, 0xff, 0xf1, 0xc5, 0x07, 0x00, 0x00,
}
