// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sonic_show_techsupport.proto

/*
Package gnoi_sonic is a generated protocol buffer package.

It is generated from these files:
	sonic_show_techsupport.proto

It has these top-level messages:
	TechsupportRequest
	TechsupportResponse
	MyEchoRequest
	MyEchoResponse
*/
package gnoi_sonic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TechsupportRequest struct {
	Date string `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
}

func (m *TechsupportRequest) Reset()                    { *m = TechsupportRequest{} }
func (m *TechsupportRequest) String() string            { return proto.CompactTextString(m) }
func (*TechsupportRequest) ProtoMessage()               {}
func (*TechsupportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TechsupportRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type TechsupportResponse struct {
	OutputFilename string `protobuf:"bytes,1,opt,name=output_filename,json=outputFilename" json:"output_filename,omitempty"`
}

func (m *TechsupportResponse) Reset()                    { *m = TechsupportResponse{} }
func (m *TechsupportResponse) String() string            { return proto.CompactTextString(m) }
func (*TechsupportResponse) ProtoMessage()               {}
func (*TechsupportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TechsupportResponse) GetOutputFilename() string {
	if m != nil {
		return m.OutputFilename
	}
	return ""
}

type MyEchoRequest struct {
	Message   string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	ErrorType string `protobuf:"bytes,2,opt,name=error_type,json=errorType" json:"error_type,omitempty"`
}

func (m *MyEchoRequest) Reset()                    { *m = MyEchoRequest{} }
func (m *MyEchoRequest) String() string            { return proto.CompactTextString(m) }
func (*MyEchoRequest) ProtoMessage()               {}
func (*MyEchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MyEchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MyEchoRequest) GetErrorType() string {
	if m != nil {
		return m.ErrorType
	}
	return ""
}

type MyEchoResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *MyEchoResponse) Reset()                    { *m = MyEchoResponse{} }
func (m *MyEchoResponse) String() string            { return proto.CompactTextString(m) }
func (*MyEchoResponse) ProtoMessage()               {}
func (*MyEchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MyEchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TechsupportRequest)(nil), "gnoi.sonic.TechsupportRequest")
	proto.RegisterType((*TechsupportResponse)(nil), "gnoi.sonic.TechsupportResponse")
	proto.RegisterType((*MyEchoRequest)(nil), "gnoi.sonic.MyEchoRequest")
	proto.RegisterType((*MyEchoResponse)(nil), "gnoi.sonic.MyEchoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SonicService service

type SonicServiceClient interface {
	ShowTechsupport(ctx context.Context, in *TechsupportRequest, opts ...grpc.CallOption) (*TechsupportResponse, error)
	MyEcho(ctx context.Context, in *MyEchoRequest, opts ...grpc.CallOption) (*MyEchoResponse, error)
}

type sonicServiceClient struct {
	cc *grpc.ClientConn
}

func NewSonicServiceClient(cc *grpc.ClientConn) SonicServiceClient {
	return &sonicServiceClient{cc}
}

func (c *sonicServiceClient) ShowTechsupport(ctx context.Context, in *TechsupportRequest, opts ...grpc.CallOption) (*TechsupportResponse, error) {
	out := new(TechsupportResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/ShowTechsupport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) MyEcho(ctx context.Context, in *MyEchoRequest, opts ...grpc.CallOption) (*MyEchoResponse, error) {
	out := new(MyEchoResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/MyEcho", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SonicService service

type SonicServiceServer interface {
	ShowTechsupport(context.Context, *TechsupportRequest) (*TechsupportResponse, error)
	MyEcho(context.Context, *MyEchoRequest) (*MyEchoResponse, error)
}

func RegisterSonicServiceServer(s *grpc.Server, srv SonicServiceServer) {
	s.RegisterService(&_SonicService_serviceDesc, srv)
}

func _SonicService_ShowTechsupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechsupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).ShowTechsupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/ShowTechsupport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).ShowTechsupport(ctx, req.(*TechsupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_MyEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyEchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).MyEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/MyEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).MyEcho(ctx, req.(*MyEchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SonicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnoi.sonic.SonicService",
	HandlerType: (*SonicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowTechsupport",
			Handler:    _SonicService_ShowTechsupport_Handler,
		},
		{
			MethodName: "MyEcho",
			Handler:    _SonicService_MyEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sonic_show_techsupport.proto",
}

func init() { proto.RegisterFile("sonic_show_techsupport.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x3d, 0x4f, 0xc3, 0x40,
	0x0c, 0x25, 0x08, 0x15, 0xd5, 0x82, 0x56, 0x32, 0x4b, 0x88, 0xf8, 0xd2, 0x2d, 0x54, 0x0c, 0x19,
	0x60, 0x47, 0x62, 0x00, 0xb1, 0xb0, 0x34, 0xd9, 0xa3, 0x10, 0x4c, 0x13, 0x89, 0xc6, 0xc7, 0x9d,
	0x8f, 0x2a, 0xbf, 0x88, 0xbf, 0x89, 0xb8, 0xf4, 0xd4, 0x56, 0x90, 0xed, 0xee, 0xbd, 0xe7, 0x67,
	0x3f, 0x1b, 0xce, 0x2c, 0xb7, 0x4d, 0x55, 0xd8, 0x9a, 0x57, 0x85, 0x50, 0x55, 0x5b, 0xa7, 0x35,
	0x1b, 0x49, 0xb5, 0x61, 0x61, 0x84, 0x45, 0xcb, 0x4d, 0xea, 0x25, 0x6a, 0x06, 0x98, 0x6f, 0x04,
	0x73, 0xfa, 0x74, 0x64, 0x05, 0x11, 0x0e, 0xde, 0x4a, 0xa1, 0x38, 0xba, 0x8a, 0x66, 0xe3, 0xb9,
	0x7f, 0xab, 0x7b, 0x38, 0xd9, 0x51, 0x5a, 0xcd, 0xad, 0x25, 0xbc, 0x86, 0x29, 0x3b, 0xd1, 0x4e,
	0x8a, 0xf7, 0xe6, 0x83, 0xda, 0x72, 0x19, 0xaa, 0x26, 0x3d, 0xfc, 0xb4, 0x46, 0xd5, 0x33, 0x1c,
	0xbf, 0x74, 0x8f, 0x55, 0xcd, 0xa1, 0x49, 0x0c, 0x87, 0x4b, 0xb2, 0xb6, 0x5c, 0x84, 0x8a, 0xf0,
	0xc5, 0x73, 0x00, 0x32, 0x86, 0x4d, 0x21, 0x9d, 0xa6, 0x78, 0xdf, 0x93, 0x63, 0x8f, 0xe4, 0x9d,
	0x26, 0x75, 0x03, 0x93, 0xe0, 0xb4, 0x1e, 0x62, 0xd0, 0xea, 0xf6, 0x3b, 0x82, 0xa3, 0xec, 0x37,
	0x69, 0x46, 0xe6, 0xab, 0xa9, 0x08, 0x73, 0x98, 0x66, 0x35, 0xaf, 0xb6, 0xa2, 0xe0, 0x45, 0xba,
	0x59, 0x48, 0xfa, 0x77, 0x1b, 0xc9, 0xe5, 0x20, 0xdf, 0xb7, 0x57, 0x7b, 0xf8, 0x00, 0xa3, 0x7e,
	0x24, 0x3c, 0xdd, 0x16, 0xef, 0x04, 0x4e, 0x92, 0xff, 0xa8, 0x60, 0xf1, 0x3a, 0xf2, 0xc7, 0xb9,
	0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x1c, 0x45, 0x1c, 0xbc, 0x01, 0x00, 0x00,
}
