// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sonic.proto

/*
Package gnoi_sonic is a generated protocol buffer package.

It is generated from these files:
	sonic.proto

It has these top-level messages:
	TechsupportRequest
	TechsupportResponse
	SumRequest
	SumResponse
	CopyConfigRequest
	CopyConfigResponse
	JwtToken
	AuthenticateRequest
	AuthenticateResponse
	RefreshRequest
	RefreshResponse
*/
package gnoi_sonic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TechsupportRequest struct {
	Input *TechsupportRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *TechsupportRequest) Reset()                    { *m = TechsupportRequest{} }
func (m *TechsupportRequest) String() string            { return proto.CompactTextString(m) }
func (*TechsupportRequest) ProtoMessage()               {}
func (*TechsupportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TechsupportRequest) GetInput() *TechsupportRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type TechsupportRequest_Input struct {
	Date string `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
}

func (m *TechsupportRequest_Input) Reset()                    { *m = TechsupportRequest_Input{} }
func (m *TechsupportRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*TechsupportRequest_Input) ProtoMessage()               {}
func (*TechsupportRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *TechsupportRequest_Input) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type TechsupportResponse struct {
	Output *TechsupportResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *TechsupportResponse) Reset()                    { *m = TechsupportResponse{} }
func (m *TechsupportResponse) String() string            { return proto.CompactTextString(m) }
func (*TechsupportResponse) ProtoMessage()               {}
func (*TechsupportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TechsupportResponse) GetOutput() *TechsupportResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type TechsupportResponse_Output struct {
	OutputFilename string `protobuf:"bytes,1,opt,name=output_filename,json=outputFilename" json:"output_filename,omitempty"`
}

func (m *TechsupportResponse_Output) Reset()                    { *m = TechsupportResponse_Output{} }
func (m *TechsupportResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*TechsupportResponse_Output) ProtoMessage()               {}
func (*TechsupportResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *TechsupportResponse_Output) GetOutputFilename() string {
	if m != nil {
		return m.OutputFilename
	}
	return ""
}

type SumRequest struct {
	Input *SumRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SumRequest) GetInput() *SumRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type SumRequest_Input struct {
	Left  int32 `protobuf:"varint,1,opt,name=left" json:"left,omitempty"`
	Right int32 `protobuf:"varint,2,opt,name=right" json:"right,omitempty"`
}

func (m *SumRequest_Input) Reset()                    { *m = SumRequest_Input{} }
func (m *SumRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*SumRequest_Input) ProtoMessage()               {}
func (*SumRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *SumRequest_Input) GetLeft() int32 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *SumRequest_Input) GetRight() int32 {
	if m != nil {
		return m.Right
	}
	return 0
}

type SumResponse struct {
	Output *SumResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SumResponse) GetOutput() *SumResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type SumResponse_Output struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *SumResponse_Output) Reset()                    { *m = SumResponse_Output{} }
func (m *SumResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*SumResponse_Output) ProtoMessage()               {}
func (*SumResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *SumResponse_Output) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CopyConfigRequest struct {
	Input *CopyConfigRequest_Input `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *CopyConfigRequest) Reset()                    { *m = CopyConfigRequest{} }
func (m *CopyConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*CopyConfigRequest) ProtoMessage()               {}
func (*CopyConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CopyConfigRequest) GetInput() *CopyConfigRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type CopyConfigRequest_Input struct {
	Source      string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Overwrite   bool   `protobuf:"varint,2,opt,name=overwrite" json:"overwrite,omitempty"`
	Destination string `protobuf:"bytes,3,opt,name=destination" json:"destination,omitempty"`
}

func (m *CopyConfigRequest_Input) Reset()                    { *m = CopyConfigRequest_Input{} }
func (m *CopyConfigRequest_Input) String() string            { return proto.CompactTextString(m) }
func (*CopyConfigRequest_Input) ProtoMessage()               {}
func (*CopyConfigRequest_Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *CopyConfigRequest_Input) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CopyConfigRequest_Input) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

func (m *CopyConfigRequest_Input) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type CopyConfigResponse struct {
	Output *CopyConfigResponse_Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *CopyConfigResponse) Reset()                    { *m = CopyConfigResponse{} }
func (m *CopyConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*CopyConfigResponse) ProtoMessage()               {}
func (*CopyConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CopyConfigResponse) GetOutput() *CopyConfigResponse_Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type CopyConfigResponse_Output struct {
	Status       int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	StatusDetail string `protobuf:"bytes,2,opt,name=status_detail,json=statusDetail" json:"status_detail,omitempty"`
}

func (m *CopyConfigResponse_Output) Reset()                    { *m = CopyConfigResponse_Output{} }
func (m *CopyConfigResponse_Output) String() string            { return proto.CompactTextString(m) }
func (*CopyConfigResponse_Output) ProtoMessage()               {}
func (*CopyConfigResponse_Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *CopyConfigResponse_Output) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CopyConfigResponse_Output) GetStatusDetail() string {
	if m != nil {
		return m.StatusDetail
	}
	return ""
}

type JwtToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	ExpiresIn   int64  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
}

func (m *JwtToken) Reset()                    { *m = JwtToken{} }
func (m *JwtToken) String() string            { return proto.CompactTextString(m) }
func (*JwtToken) ProtoMessage()               {}
func (*JwtToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *JwtToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *JwtToken) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JwtToken) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type AuthenticateRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthenticateRequest) Reset()                    { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()               {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	Token *JwtToken `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *AuthenticateResponse) Reset()                    { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()               {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AuthenticateResponse) GetToken() *JwtToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type RefreshRequest struct {
}

func (m *RefreshRequest) Reset()                    { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string            { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()               {}
func (*RefreshRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type RefreshResponse struct {
	Token *JwtToken `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *RefreshResponse) Reset()                    { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string            { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()               {}
func (*RefreshResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RefreshResponse) GetToken() *JwtToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*TechsupportRequest)(nil), "gnoi.sonic.TechsupportRequest")
	proto.RegisterType((*TechsupportRequest_Input)(nil), "gnoi.sonic.TechsupportRequest.Input")
	proto.RegisterType((*TechsupportResponse)(nil), "gnoi.sonic.TechsupportResponse")
	proto.RegisterType((*TechsupportResponse_Output)(nil), "gnoi.sonic.TechsupportResponse.Output")
	proto.RegisterType((*SumRequest)(nil), "gnoi.sonic.SumRequest")
	proto.RegisterType((*SumRequest_Input)(nil), "gnoi.sonic.SumRequest.Input")
	proto.RegisterType((*SumResponse)(nil), "gnoi.sonic.SumResponse")
	proto.RegisterType((*SumResponse_Output)(nil), "gnoi.sonic.SumResponse.Output")
	proto.RegisterType((*CopyConfigRequest)(nil), "gnoi.sonic.CopyConfigRequest")
	proto.RegisterType((*CopyConfigRequest_Input)(nil), "gnoi.sonic.CopyConfigRequest.Input")
	proto.RegisterType((*CopyConfigResponse)(nil), "gnoi.sonic.CopyConfigResponse")
	proto.RegisterType((*CopyConfigResponse_Output)(nil), "gnoi.sonic.CopyConfigResponse.Output")
	proto.RegisterType((*JwtToken)(nil), "gnoi.sonic.JwtToken")
	proto.RegisterType((*AuthenticateRequest)(nil), "gnoi.sonic.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "gnoi.sonic.AuthenticateResponse")
	proto.RegisterType((*RefreshRequest)(nil), "gnoi.sonic.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "gnoi.sonic.RefreshResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SonicService service

type SonicServiceClient interface {
	ShowTechsupport(ctx context.Context, in *TechsupportRequest, opts ...grpc.CallOption) (*TechsupportResponse, error)
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	CopyConfig(ctx context.Context, in *CopyConfigRequest, opts ...grpc.CallOption) (*CopyConfigResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
}

type sonicServiceClient struct {
	cc *grpc.ClientConn
}

func NewSonicServiceClient(cc *grpc.ClientConn) SonicServiceClient {
	return &sonicServiceClient{cc}
}

func (c *sonicServiceClient) ShowTechsupport(ctx context.Context, in *TechsupportRequest, opts ...grpc.CallOption) (*TechsupportResponse, error) {
	out := new(TechsupportResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/ShowTechsupport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) CopyConfig(ctx context.Context, in *CopyConfigRequest, opts ...grpc.CallOption) (*CopyConfigResponse, error) {
	out := new(CopyConfigResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/CopyConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonicServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := grpc.Invoke(ctx, "/gnoi.sonic.SonicService/Refresh", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SonicService service

type SonicServiceServer interface {
	ShowTechsupport(context.Context, *TechsupportRequest) (*TechsupportResponse, error)
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	CopyConfig(context.Context, *CopyConfigRequest) (*CopyConfigResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
}

func RegisterSonicServiceServer(s *grpc.Server, srv SonicServiceServer) {
	s.RegisterService(&_SonicService_serviceDesc, srv)
}

func _SonicService_ShowTechsupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechsupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).ShowTechsupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/ShowTechsupport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).ShowTechsupport(ctx, req.(*TechsupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_CopyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).CopyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/CopyConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).CopyConfig(ctx, req.(*CopyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonicService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonicServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gnoi.sonic.SonicService/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonicServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SonicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gnoi.sonic.SonicService",
	HandlerType: (*SonicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowTechsupport",
			Handler:    _SonicService_ShowTechsupport_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _SonicService_Sum_Handler,
		},
		{
			MethodName: "CopyConfig",
			Handler:    _SonicService_CopyConfig_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _SonicService_Authenticate_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _SonicService_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sonic.proto",
}

func init() { proto.RegisterFile("sonic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xed, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0xe9, 0x5a, 0xd6, 0xdb, 0xb2, 0xc1, 0xdd, 0x34, 0xa6, 0xec, 0x83, 0xe2, 0xf1, 0x25,
	0x7e, 0x54, 0x5a, 0x91, 0x10, 0x20, 0x0d, 0x09, 0x36, 0x90, 0x86, 0x34, 0x21, 0xa5, 0xfd, 0x5f,
	0x42, 0x7a, 0xdb, 0x5a, 0xb4, 0x71, 0xb0, 0x9d, 0x95, 0xbd, 0xc1, 0x9e, 0x81, 0x97, 0xe0, 0x15,
	0x51, 0x6d, 0x27, 0x4d, 0xb6, 0x76, 0x88, 0x7f, 0xbe, 0xc7, 0xe7, 0x7e, 0x9c, 0x63, 0x3b, 0x81,
	0xba, 0x12, 0x11, 0x0f, 0x5b, 0xb1, 0x14, 0x5a, 0x20, 0x0c, 0x23, 0xc1, 0x5b, 0x06, 0x61, 0x13,
	0xc0, 0x2e, 0x85, 0x23, 0x95, 0xc4, 0xb1, 0x90, 0xda, 0xa7, 0x9f, 0x09, 0x29, 0x8d, 0xef, 0xa0,
	0xc2, 0xa3, 0x38, 0xd1, 0x3b, 0xa5, 0x66, 0xe9, 0x45, 0xbd, 0xfd, 0xa4, 0x35, 0xcf, 0x68, 0xdd,
	0xa4, 0xb7, 0xce, 0x66, 0x5c, 0xdf, 0xa6, 0x78, 0xbb, 0x50, 0x31, 0x31, 0x22, 0xac, 0xf6, 0x03,
	0x4d, 0xa6, 0x46, 0xcd, 0x37, 0x6b, 0x76, 0x55, 0x82, 0xcd, 0x42, 0x01, 0x15, 0x8b, 0x48, 0x11,
	0xbe, 0x87, 0xaa, 0x48, 0xf4, 0xbc, 0xe3, 0xb3, 0xa5, 0x1d, 0x6d, 0x42, 0xeb, 0xab, 0x61, 0xfb,
	0x2e, 0xcb, 0x3b, 0x82, 0xaa, 0x45, 0xf0, 0x39, 0x6c, 0x58, 0xac, 0x37, 0xe0, 0x63, 0x8a, 0x82,
	0x49, 0x3a, 0xc0, 0xba, 0x85, 0x3f, 0x3b, 0x94, 0x29, 0x80, 0x4e, 0x32, 0x49, 0x15, 0xb7, 0x8b,
	0x8a, 0xf7, 0xf2, 0xfd, 0xe7, 0xb4, 0xa2, 0xd2, 0xa3, 0x9c, 0xd2, 0x31, 0x0d, 0x6c, 0x6e, 0xc5,
	0x37, 0x6b, 0xdc, 0x82, 0x8a, 0xe4, 0xc3, 0x91, 0xde, 0xb9, 0x63, 0x40, 0x1b, 0xb0, 0x21, 0xd4,
	0x4d, 0x35, 0x27, 0xfb, 0xf5, 0x35, 0xd9, 0x07, 0x37, 0xda, 0x2e, 0x96, 0xdb, 0xcc, 0xe4, 0x6e,
	0x43, 0x55, 0x92, 0x4a, 0xc6, 0x69, 0x73, 0x17, 0xb1, 0x3f, 0x25, 0x78, 0x70, 0x22, 0xe2, 0xcb,
	0x13, 0x11, 0x0d, 0xf8, 0x30, 0x55, 0xf9, 0xb6, 0xa8, 0xf2, 0x30, 0xdf, 0xee, 0x06, 0xbb, 0x28,
	0xb6, 0x97, 0x8a, 0xdd, 0x86, 0xaa, 0x12, 0x89, 0x0c, 0x53, 0x5f, 0x5d, 0x84, 0x7b, 0x50, 0x13,
	0x17, 0x24, 0xa7, 0x92, 0x6b, 0x32, 0xa2, 0xd7, 0xfc, 0x39, 0x80, 0x4d, 0xa8, 0xf7, 0x49, 0x69,
	0x1e, 0x05, 0x9a, 0x8b, 0x68, 0xa7, 0x6c, 0x52, 0xf3, 0x10, 0xfb, 0x5d, 0x02, 0xcc, 0xcf, 0xe0,
	0x2c, 0x3a, 0xbe, 0x66, 0xd1, 0xd3, 0x65, 0x33, 0x2f, 0x76, 0xea, 0x53, 0xde, 0x29, 0xa5, 0x03,
	0x9d, 0xa8, 0xd4, 0x29, 0x1b, 0xe1, 0x21, 0xdc, 0xb3, 0xab, 0x5e, 0x9f, 0x74, 0xc0, 0xc7, 0x66,
	0xf6, 0x9a, 0xdf, 0xb0, 0xe0, 0xa9, 0xc1, 0xd8, 0x37, 0x58, 0xfb, 0x32, 0xd5, 0x5d, 0xf1, 0x83,
	0x22, 0x7c, 0x0c, 0x8d, 0x20, 0x0c, 0x49, 0xa9, 0x9e, 0x9e, 0xc5, 0xce, 0x86, 0xba, 0xc5, 0x2c,
	0x05, 0x61, 0x55, 0x5f, 0xc6, 0xe4, 0x4a, 0x99, 0x35, 0xee, 0x03, 0xd0, 0xaf, 0x98, 0x4b, 0x52,
	0x3d, 0x6e, 0x0d, 0x28, 0xfb, 0x35, 0x87, 0x9c, 0x45, 0xec, 0x1c, 0x36, 0x3f, 0x24, 0x7a, 0x44,
	0x91, 0xe6, 0x61, 0xa0, 0x29, 0x3d, 0x31, 0x0f, 0xd6, 0x12, 0x45, 0x32, 0x77, 0x8f, 0xb3, 0x78,
	0xb6, 0x17, 0x07, 0x4a, 0x4d, 0x85, 0xec, 0xbb, 0x4e, 0x59, 0xcc, 0x3e, 0xc2, 0x56, 0xb1, 0x9c,
	0xb3, 0xf3, 0x25, 0x54, 0xba, 0xd9, 0xd4, 0xf5, 0xf6, 0x56, 0xde, 0xcd, 0x54, 0xa1, 0x6f, 0x29,
	0xec, 0x3e, 0xac, 0xfb, 0x34, 0x90, 0xa4, 0x46, 0x6e, 0x1a, 0x76, 0x0c, 0x1b, 0x19, 0xf2, 0xff,
	0x05, 0xdb, 0x57, 0x65, 0x68, 0x74, 0x66, 0x3b, 0x1d, 0x92, 0x17, 0x3c, 0x24, 0xec, 0xc2, 0x46,
	0x67, 0x24, 0xa6, 0xb9, 0x07, 0x8e, 0x07, 0xb7, 0x7f, 0x6b, 0xbc, 0x47, 0xff, 0xf8, 0x32, 0xb0,
	0x15, 0x7c, 0x03, 0xe5, 0x4e, 0x32, 0xc1, 0xed, 0xc5, 0x6f, 0xd8, 0x7b, 0xb8, 0xe4, 0x91, 0xb1,
	0x15, 0x3c, 0x07, 0x98, 0x5f, 0x29, 0xdc, 0xbf, 0xf5, 0x79, 0x78, 0x07, 0xb7, 0xdf, 0x44, 0xb6,
	0x82, 0x1d, 0x68, 0xe4, 0x0f, 0x01, 0x0b, 0xb3, 0x2f, 0x38, 0x6d, 0xaf, 0xb9, 0x9c, 0x90, 0x15,
	0x3d, 0x85, 0xbb, 0xee, 0x0c, 0xd0, 0xcb, 0xd3, 0x8b, 0x47, 0xe5, 0xed, 0x2e, 0xdc, 0x4b, 0xab,
	0x7c, 0xaf, 0x9a, 0x5f, 0xc1, 0xab, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xe7, 0xf7, 0x65,
	0x19, 0x06, 0x00, 0x00,
}
